### ISSUE TITLE
jq command not found in certspotter

### ISSUE THREAD

**Issue by 0xSnowmn** [nahamsec/recon_profile#3]
When i run certspotter i get "bash: jq: command not found" 
how i can solve this?

**Comment by sawzeeyy** [comment]
Hi @yghonem14,

`jq` is a lightweight and flexible command-line JSON processor.

You can install on Linux with the following command:

```
sudo apt-get install jq
```

More information on installation at https://stedolan.github.io/jq/download/

**Comment by 0xSnowmn** [comment]
Solved,Thank you!

**Comment by raz455** [comment]
For Mac OS users `brew install jq`
